name: run-tests
on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
  pull_request_target:
    types: [opened, edited]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    env:
      GO_VERSION: "~1.20"
      GO111MODULE: "on"
      USE_CODECOV: true

    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download and tidy Go modules
        run: go mod download && go mod tidy

      - name: Run Tests with Coverage
        if: ${{success()}}
        run: go test -cover -coverprofile coverage.out -v ./cmd/**

      - name: Upload coverage reports to Codecov
        if: ${{ success() && env.USE_CODECOV }}
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.out
